name: Deploy Frontend

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy project files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/ubuntu/frontend/"

      - name: Build Docker image and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/frontend

            # Docker image build karo
            docker build -t ammar456/feedfront-helm-img:${{ github.sha }} .

            # Docker Hub pe push karo
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker push ammar456/feedfront-helm-img:${{ github.sha }}

            # Helm upgrade karo
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
            helm upgrade frontend-chart /home/ubuntu/frontend/helm \
              --namespace production \
              --set image.tag=${{ github.sha }}

            # Purani images clean karo
            docker image prune -f
